// <auto-generated />
using System;
using FridayNight.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FridayNight.DAL.Migrations
{
    [DbContext(typeof(FNContext))]
    [Migration("20200826230402_AddedGuidAutoGeneration")]
    partial class AddedGuidAutoGeneration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("FridayNight.DAL.Model.Abstract.ActionRecordBase", b =>
                {
                    b.Property<Guid>("Uid")
                        .HasColumnName("uid")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTime")
                        .HasColumnName("date_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnName("discriminator")
                        .HasColumnType("text");

                    b.HasKey("Uid")
                        .HasName("pk_action_record_base");

                    b.ToTable("action_records");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ActionRecordBase");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.Abstract.LinkContainerBase", b =>
                {
                    b.Property<Guid>("Uid")
                        .HasColumnName("uid")
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnName("discriminator")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnName("url")
                        .HasColumnType("text");

                    b.HasKey("Uid")
                        .HasName("pk_link_container_base");

                    b.ToTable("link_containers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("LinkContainerBase");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.Abstract.RatingBase", b =>
                {
                    b.Property<Guid>("Uid")
                        .HasColumnName("uid")
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnName("discriminator")
                        .HasColumnType("text");

                    b.HasKey("Uid")
                        .HasName("pk_rating_base");

                    b.ToTable("ratings");

                    b.HasDiscriminator<string>("Discriminator").HasValue("RatingBase");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.Abstract.ResourceBase", b =>
                {
                    b.Property<Guid>("Uid")
                        .HasColumnName("uid")
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnName("discriminator")
                        .HasColumnType("text");

                    b.Property<byte[]>("Resource")
                        .HasColumnName("resource")
                        .HasColumnType("bytea");

                    b.HasKey("Uid")
                        .HasName("pk_resource_base");

                    b.ToTable("resources");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ResourceBase");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.Account", b =>
                {
                    b.Property<Guid>("Uid")
                        .HasColumnName("uid")
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnName("discriminator")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnName("password")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnName("phone")
                        .HasColumnType("text");

                    b.HasKey("Uid")
                        .HasName("pk_accounts");

                    b.ToTable("accounts");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Account");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.Contact", b =>
                {
                    b.Property<Guid>("Uid")
                        .HasColumnName("uid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocationUid")
                        .HasColumnName("location_uid")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnName("phone")
                        .HasColumnType("text");

                    b.HasKey("Uid")
                        .HasName("pk_contacts");

                    b.HasIndex("LocationUid")
                        .HasName("ix_contacts_location_uid");

                    b.ToTable("contacts");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.FriendlyCharge", b =>
                {
                    b.Property<Guid>("Uid")
                        .HasColumnName("uid")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnName("amount")
                        .HasColumnType("numeric");

                    b.Property<int>("State")
                        .HasColumnName("state")
                        .HasColumnType("integer");

                    b.HasKey("Uid")
                        .HasName("pk_friendly_charges");

                    b.ToTable("friendly_charges");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.LivePerformance", b =>
                {
                    b.Property<Guid>("Uid")
                        .HasColumnName("uid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BandUid")
                        .HasColumnName("band_uid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChargeUid")
                        .HasColumnName("charge_uid")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnName("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnName("duration")
                        .HasColumnType("interval");

                    b.Property<bool>("IsApproved")
                        .HasColumnName("is_approved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrivate")
                        .HasColumnName("is_private")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LocationUid")
                        .HasColumnName("location_uid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PlaceUid")
                        .HasColumnName("place_uid")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnName("state")
                        .HasColumnType("integer");

                    b.HasKey("Uid")
                        .HasName("pk_live_performances");

                    b.HasIndex("BandUid")
                        .HasName("ix_live_performances_band_uid");

                    b.HasIndex("ChargeUid")
                        .HasName("ix_live_performances_charge_uid");

                    b.HasIndex("LocationUid")
                        .HasName("ix_live_performances_location_uid");

                    b.HasIndex("PlaceUid")
                        .HasName("ix_live_performances_place_uid");

                    b.ToTable("live_performances");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.Location", b =>
                {
                    b.Property<Guid>("Uid")
                        .HasColumnName("uid")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnName("address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnName("city")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnName("country")
                        .HasColumnType("text");

                    b.Property<Guid?>("PlaceUid")
                        .HasColumnName("place_uid")
                        .HasColumnType("uuid");

                    b.HasKey("Uid")
                        .HasName("pk_locations");

                    b.HasIndex("PlaceUid")
                        .HasName("ix_locations_place_uid");

                    b.ToTable("locations");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.MusicPreferences", b =>
                {
                    b.Property<Guid>("Uid")
                        .HasColumnName("uid")
                        .HasColumnType("uuid");

                    b.HasKey("Uid")
                        .HasName("pk_music_preferences");

                    b.ToTable("music_preferences");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.MusicStyle", b =>
                {
                    b.Property<Guid>("Uid")
                        .HasColumnName("uid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BandUid")
                        .HasColumnName("band_uid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MusicPreferencesUid")
                        .HasColumnName("music_preferences_uid")
                        .HasColumnType("uuid");

                    b.Property<int>("Name")
                        .HasColumnName("name")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TrackUid")
                        .HasColumnName("track_uid")
                        .HasColumnType("uuid");

                    b.HasKey("Uid")
                        .HasName("pk_music_styles");

                    b.HasIndex("BandUid")
                        .HasName("ix_music_styles_band_uid");

                    b.HasIndex("MusicPreferencesUid")
                        .HasName("ix_music_styles_music_preferences_uid");

                    b.HasIndex("TrackUid")
                        .HasName("ix_music_styles_track_uid");

                    b.ToTable("music_styles");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.Track", b =>
                {
                    b.Property<Guid>("Uid")
                        .HasColumnName("uid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OwnerUid")
                        .HasColumnName("owner_uid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RatingUid")
                        .HasColumnName("rating_uid")
                        .HasColumnType("uuid");

                    b.Property<string>("TrackName")
                        .HasColumnName("track_name")
                        .HasColumnType("text");

                    b.HasKey("Uid")
                        .HasName("pk_tracks");

                    b.HasIndex("OwnerUid")
                        .HasName("ix_tracks_owner_uid");

                    b.HasIndex("RatingUid")
                        .HasName("ix_tracks_rating_uid");

                    b.ToTable("tracks");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.ViewedBands", b =>
                {
                    b.HasBaseType("FridayNight.DAL.Model.Abstract.ActionRecordBase");

                    b.Property<Guid?>("BandUid")
                        .HasColumnName("band_uid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PlaceUid")
                        .HasColumnName("place_uid")
                        .HasColumnType("uuid");

                    b.HasIndex("BandUid")
                        .HasName("ix_viewed_bands_band_uid");

                    b.HasIndex("PlaceUid")
                        .HasName("ix_viewed_bands_place_uid");

                    b.HasDiscriminator().HasValue("ViewedBands");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.InstagramLink", b =>
                {
                    b.HasBaseType("FridayNight.DAL.Model.Abstract.LinkContainerBase");

                    b.HasDiscriminator().HasValue("InstagramLink");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.YoutubeVideoLink", b =>
                {
                    b.HasBaseType("FridayNight.DAL.Model.Abstract.LinkContainerBase");

                    b.HasDiscriminator().HasValue("YoutubeVideoLink");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.BandRating", b =>
                {
                    b.HasBaseType("FridayNight.DAL.Model.Abstract.RatingBase");

                    b.Property<int>("LikesCount")
                        .HasColumnName("likes_count")
                        .HasColumnType("integer");

                    b.Property<int>("OpenedContactCount")
                        .HasColumnName("opened_contact_count")
                        .HasColumnType("integer");

                    b.Property<int>("ViewsCount")
                        .HasColumnName("views_count")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("BandRating");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.TrackRating", b =>
                {
                    b.HasBaseType("FridayNight.DAL.Model.Abstract.RatingBase");

                    b.Property<int>("ListenedCount")
                        .HasColumnName("listened_count")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("TrackRating");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.Photo", b =>
                {
                    b.HasBaseType("FridayNight.DAL.Model.Abstract.ResourceBase");

                    b.Property<Guid?>("BandUid")
                        .HasColumnName("band_uid")
                        .HasColumnType("uuid");

                    b.HasIndex("BandUid")
                        .HasName("ix_photos_band_uid");

                    b.HasDiscriminator().HasValue("Photo");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.Band", b =>
                {
                    b.HasBaseType("FridayNight.DAL.Model.Account");

                    b.Property<Guid?>("ContactUid")
                        .HasColumnName("contact_uid")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("text");

                    b.Property<Guid?>("InstagramLinkUid")
                        .HasColumnName("instagram_link_uid")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<Guid?>("PhotoCoverUid")
                        .HasColumnName("photo_cover_uid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RatingUid")
                        .HasColumnName("rating_uid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("YoutubeVideoUid")
                        .HasColumnName("youtube_video_uid")
                        .HasColumnType("uuid");

                    b.HasIndex("ContactUid")
                        .HasName("ix_accounts_contact_uid");

                    b.HasIndex("InstagramLinkUid")
                        .HasName("ix_accounts_instagram_link_uid");

                    b.HasIndex("PhotoCoverUid")
                        .HasName("ix_accounts_photo_cover_uid");

                    b.HasIndex("RatingUid")
                        .HasName("ix_accounts_rating_uid");

                    b.HasIndex("YoutubeVideoUid")
                        .HasName("ix_accounts_youtube_video_uid");

                    b.HasDiscriminator().HasValue("Band");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.Place", b =>
                {
                    b.HasBaseType("FridayNight.DAL.Model.Account");

                    b.Property<Guid?>("ContactUid")
                        .HasColumnName("Place_contact_uid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MusicPreferencesUid")
                        .HasColumnName("music_preferences_uid")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnName("Place_name")
                        .HasColumnType("text");

                    b.Property<int>("PlaceType")
                        .HasColumnName("place_type")
                        .HasColumnType("integer");

                    b.HasIndex("ContactUid")
                        .HasName("ix_accounts_contact_uid1");

                    b.HasIndex("MusicPreferencesUid")
                        .HasName("ix_accounts_music_preferences_uid");

                    b.HasDiscriminator().HasValue("Place");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.User", b =>
                {
                    b.HasBaseType("FridayNight.DAL.Model.Account");

                    b.Property<string>("FirstName")
                        .HasColumnName("first_name")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnName("last_name")
                        .HasColumnType("text");

                    b.Property<Guid?>("MusicPreferencesUid")
                        .HasColumnName("User_music_preferences_uid")
                        .HasColumnType("uuid");

                    b.HasIndex("MusicPreferencesUid")
                        .HasName("ix_accounts_music_preferences_uid1");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.Contact", b =>
                {
                    b.HasOne("FridayNight.DAL.Model.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationUid")
                        .HasConstraintName("fk_contacts_locations_location_uid");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.LivePerformance", b =>
                {
                    b.HasOne("FridayNight.DAL.Model.Band", "Band")
                        .WithMany("Performances")
                        .HasForeignKey("BandUid")
                        .HasConstraintName("fk_live_performances_accounts_band_uid");

                    b.HasOne("FridayNight.DAL.Model.FriendlyCharge", "Charge")
                        .WithMany()
                        .HasForeignKey("ChargeUid")
                        .HasConstraintName("fk_live_performances_friendly_charges_charge_uid");

                    b.HasOne("FridayNight.DAL.Model.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationUid")
                        .HasConstraintName("fk_live_performances_locations_location_uid");

                    b.HasOne("FridayNight.DAL.Model.Place", "Place")
                        .WithMany("PerformanceHistory")
                        .HasForeignKey("PlaceUid")
                        .HasConstraintName("fk_live_performances_accounts_place_uid");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.Location", b =>
                {
                    b.HasOne("FridayNight.DAL.Model.Place", null)
                        .WithMany("Locations")
                        .HasForeignKey("PlaceUid")
                        .HasConstraintName("fk_locations_accounts_place_uid");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.MusicStyle", b =>
                {
                    b.HasOne("FridayNight.DAL.Model.Band", null)
                        .WithMany("MusicStyle")
                        .HasForeignKey("BandUid")
                        .HasConstraintName("fk_music_styles_accounts_band_uid");

                    b.HasOne("FridayNight.DAL.Model.MusicPreferences", null)
                        .WithMany("MusicStyles")
                        .HasForeignKey("MusicPreferencesUid")
                        .HasConstraintName("fk_music_styles_music_preferences_music_preferences_uid");

                    b.HasOne("FridayNight.DAL.Model.Track", null)
                        .WithMany("MusicStyle")
                        .HasForeignKey("TrackUid")
                        .HasConstraintName("fk_music_styles_tracks_track_uid");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.Track", b =>
                {
                    b.HasOne("FridayNight.DAL.Model.Band", "Owner")
                        .WithMany("Tracks")
                        .HasForeignKey("OwnerUid")
                        .HasConstraintName("fk_tracks_accounts_owner_uid");

                    b.HasOne("FridayNight.DAL.Model.TrackRating", "Rating")
                        .WithMany()
                        .HasForeignKey("RatingUid")
                        .HasConstraintName("fk_tracks_rating_base_rating_uid");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.ViewedBands", b =>
                {
                    b.HasOne("FridayNight.DAL.Model.Band", "Band")
                        .WithMany()
                        .HasForeignKey("BandUid")
                        .HasConstraintName("fk_viewed_bands_accounts_band_uid");

                    b.HasOne("FridayNight.DAL.Model.Place", null)
                        .WithMany("ViewedBands")
                        .HasForeignKey("PlaceUid")
                        .HasConstraintName("fk_viewed_bands_accounts_place_uid");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.Photo", b =>
                {
                    b.HasOne("FridayNight.DAL.Model.Band", null)
                        .WithMany("Photos")
                        .HasForeignKey("BandUid")
                        .HasConstraintName("fk_photos_accounts_band_uid");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.Band", b =>
                {
                    b.HasOne("FridayNight.DAL.Model.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactUid")
                        .HasConstraintName("fk_accounts_contacts_contact_uid");

                    b.HasOne("FridayNight.DAL.Model.InstagramLink", "InstagramLink")
                        .WithMany()
                        .HasForeignKey("InstagramLinkUid")
                        .HasConstraintName("fk_accounts_link_container_base_instagram_link_uid");

                    b.HasOne("FridayNight.DAL.Model.Photo", "PhotoCover")
                        .WithMany()
                        .HasForeignKey("PhotoCoverUid")
                        .HasConstraintName("fk_accounts_resource_base_photo_cover_uid");

                    b.HasOne("FridayNight.DAL.Model.BandRating", "Rating")
                        .WithMany()
                        .HasForeignKey("RatingUid")
                        .HasConstraintName("fk_accounts_rating_base_rating_uid");

                    b.HasOne("FridayNight.DAL.Model.YoutubeVideoLink", "YoutubeVideo")
                        .WithMany()
                        .HasForeignKey("YoutubeVideoUid")
                        .HasConstraintName("fk_accounts_link_container_base_youtube_video_uid");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.Place", b =>
                {
                    b.HasOne("FridayNight.DAL.Model.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactUid")
                        .HasConstraintName("fk_accounts_contacts_contact_uid1");

                    b.HasOne("FridayNight.DAL.Model.MusicPreferences", "MusicPreferences")
                        .WithMany()
                        .HasForeignKey("MusicPreferencesUid")
                        .HasConstraintName("fk_accounts_music_preferences_music_preferences_uid");
                });

            modelBuilder.Entity("FridayNight.DAL.Model.User", b =>
                {
                    b.HasOne("FridayNight.DAL.Model.MusicPreferences", "MusicPreferences")
                        .WithMany()
                        .HasForeignKey("MusicPreferencesUid")
                        .HasConstraintName("fk_accounts_music_preferences_music_preferences_uid1");
                });
#pragma warning restore 612, 618
        }
    }
}
